version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pii-test-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      # Persistent data storage
      - postgres_data:/var/lib/postgresql/data
      # Auto-initialize database schema on first run
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql:ro

    networks:
      - pii-test-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  pii-test-network:
    driver: bridge
